name: Backend Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  lintjob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
            

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint the code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


    - name: print message
      run: echo "lint build is running"

  testjob:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4.1.7

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 

    - name: Test with unittest
      run: |
        python -m unittest disco

  buildjob:
    runs-on: ubuntu-latest
    needs: [lintjob, testjob]


    steps:
    - name: checkout code
      uses: actions/checkout@v4.1.7

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: install depedencies
      run: cd ./starter/frontend && npm ci

    - name: run tests
      run:  cd ./starter/frontend && npm run test

    - name: print message
      run: echo "test build is running"

