name: frontend ci 

on:
  workflow_dispatch:

  push:
    branches:
      -main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
            

    - name: setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install depedencies
      uses: cd starter/fronend && npm ci

    - name: run lint
      uses: cd starter/fronend && npm run lint

    - name: print message
      uses: echo "lint build is running"

  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4.1.7

    - name: setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install depedencies
      uses: cd starter/fronend &&  npm ci

    - name: run tests
      uses: cd starter/fronend && npm run test

    - name: print message
      uses: echo "test build is running"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]


    steps:
    - name: checkout code
      uses: actions/checkout@v4.1.7

    - name: setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install depedencies
      uses: npm ci

    - name: run tests
      uses: npm run test

    - name: print message
      uses: echo "test build is running"

